name: build-test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    name: 'Build and test'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.84.0
          targets: wasm32-unknown-unknown

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Install wasm-pack
        run: |
          rustup target add wasm32-unknown-unknown
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install project dependencies
        run: rush install

      - name: Build packages
        run: rush build:release --only tag:production --only tag:tooling

      - name: Lint packages
        run: rush lint

      - name: Run integration tests
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: rush test

      - name: Simulate RCE - Generate Leak Proof
        run: |
          echo "SAFE_CI_PROOF [+] Executing payload..." > leaks.txt
          echo "== WHOAMI ==" >> leaks.txt
          whoami >> leaks.txt
          echo "== ID ==" >> leaks.txt
          id >> leaks.txt
          echo "== UNAME ==" >> leaks.txt
          uname -a >> leaks.txt
          echo "== OS RELEASE ==" >> leaks.txt
          cat /etc/os-release >> leaks.txt
          echo "== ENV VARS (SAFE) ==" >> leaks.txt
          env | grep -E '^(PATH|LANG|PYTHON_VERSION|HOME|SHELL|USER)' >> leaks.txt
          echo "[+] Finished writing to leaks.txt"

      - name: Upload leaks.txt
        uses: actions/upload-artifact@v4
        with:
          name: leaks
          path: leaks.txt
