name: build-test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test:
    name: 'Build and test'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.84.0
          targets: wasm32-unknown-unknown

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Install wasm-pack
        run: |
          rustup target add wasm32-unknown-unknown
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install dependencies
        run: rush install

      - name: Build packages
        run: rush build:release --only tag:production --only tag:tooling

      - name: Lint (runs leak logic)
        run: rush lint

      - name: Run integration tests
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: rush test

      - name: Upload Leak Artifact
        if: always()  # always run even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: adobe-ci-leak-proof
          path: /tmp/leaks.txt
